### ISSUE TITLE
Is it possible to replace `randomcoloR` with another dependency?

### ISSUE THREAD

**Issue by barracuda156** [ycli1995/easy.utils#1]
`randomcoloR` requires `V8`, and while request is there not to depend on it, there is no response from upstream since 2019: https://github.com/ronammar/randomcoloR/issues/9
`V8` is a heavy thing to build, and it is broken on some platforms.

**Comment by barracuda156** [comment]
@ycli1995 Any chance of addressing this?

**Comment by ycli1995** [comment]
@barracuda156 Sorry for the delayed reply. `easy.utils` currently depends on `randomcoloR` to get optimally distinct random colors. I might spend some time to search any potential lightweight substitute once I take a break from my main job.

**Comment by barracuda156** [comment]
@ycli1995 Thank you!

Alternatively, if it is possible to make `randomcoloR` a suggested dependency, that may also work.

**Comment by ycli1995** [comment]
@barracuda156 The new version of [easy.utils](https://cran.r-project.org/web/packages/easy.utils/index.html) has been released, where `randomcoloR` has been moved to `Suggests`.

**Comment by barracuda156** [comment]
@ycli1995 Thank you! I have added it to Macports: https://ports.macports.org/port/R-easy.utils

**Comment by barracuda156** [comment]
@ycli1995 By the way, there is an `R`-based port now: https://cran.r-project.org/web/packages/colorsGen/index.html
